const ROLES = Object.freeze({
  CUSTOMER: "CUSTOMER",
  WORKER: "WORKER",
  COOPERATIVE_ADMIN: "COOPERATIVE_ADMIN",
  FEDERATION_ADMIN: "FEDERATION_ADMIN",
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
});

const ALL_ROLES = Object.values(ROLES);

module.exports = { ROLES, ALL_ROLES };
